#ifndef LEXER_HEADER_H
#define LEXER_HEADER_H

typedef enum{
    //Single character tokens
    TOKEN_OPEN_PARENTHESIS, TOKEN_CLOSE_PARENTHESIS,
    TOKEN_OPEN_BRACE, TOKEN_CLOSE_BRACE,
    TOKEN_PLUS, TOKEN_MINUS,
    TOKEN_STAR, TOKEN_SLASH,
    TOKEN_SEMICOLON, 

    //One or two character tokens
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_SMALLER, TOKEN_SMALLER_EQUAL,
    TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    
    //Literals
    TOKEN_IDENTIFIER, TOKEN_INTEGER,

    //Keywords
    TOKEN_IF, TOKEN_ELSE,
    TOKEN_INT, TOKEN_WHILE,
    TOKEN_PRINT

}token_type;

#endif